# Generated by Django 5.1.5 on 2025-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parent_email_class_alter_student_current_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='070000000', max_length=15),
            preserve_default=False,
        ),
    ]
