# Generated by Django 5.1.5 on 2025-10-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subject_remove_class_teacher_class_class_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subjects',
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', to='main.subject'),
        ),
    ]
