# Generated by Django 5.1.5 on 2025-10-20 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_management_user_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfeestructure',
            name='amount_required',
        ),
        migrations.RemoveField(
            model_name='schoolfeestructure',
            name='term',
        ),
        migrations.RemoveField(
            model_name='schoolfeestructure',
            name='year',
        ),
        migrations.AddField(
            model_name='schoolfeestructure',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.session'),
            preserve_default=False,
        ),
    ]
