# Generated by Django 5.1.5 on 2025-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_schoolfeestructure_amount_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolfeestructure',
            old_name='class_name',
            new_name='class_room',
        ),
    ]
