# Generated by Django 5.1.5 on 2025-10-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_class_name_schoolfeestructure_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeestructure',
            name='total_amount_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
