# Generated by Django 5.1.5 on 2025-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_schoolfeestructure_total_amount_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecomponent',
            name='structure',
        ),
        migrations.AddField(
            model_name='schoolfeestructure',
            name='components',
            field=models.ManyToManyField(related_name='fee_structures', to='main.feecomponent'),
        ),
    ]
