# Generated by Django 5.1.5 on 2025-10-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_feecomponent_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade_components', models.ManyToManyField(related_name='grade_components', to='main.grade')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='grading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='main.gradingsystem'),
        ),
    ]
