# Generated by Django 5.1.5 on 2025-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_gradingsystem_classroom_grading_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='grading_system',
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='grading_systems', to='main.classroom'),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='grading_systems', to='main.subject'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('term', 'year'), name='unique_term_year'),
        ),
    ]
